cdnDomains:

  chinacache:
    mybucket:
      - host: www.acme.com.cn
      - action: purge
    mybucket-02:
      - action: load
      - host: www.wily-coyotte.com.cn

  edgecast:
    mybucket:
      - action: load 
      - host: www.acme.co
    mybucket-02:
      - { host: www.acme.it, platform: large }
      - { host: www.acme.fr, platform: large }

  akamai:
    mybucket-03:
      - host: www.xx.co
    mybucket-02:
      - host: www.acme.it
    mybucket:
      - { host: www.acme.co , platform: staging  }
      - host: www.acme.co

  highwinds:
    mybucket:
      - host: www.acme.co

  cloudflare:
    mybucket:
      # You must use the zone id as the platform identifier
      - { host: www.acme.co , platform: cloudflare-zone-id  }

  fastly:
    mybucket:
      - host: www.acme.co
      
# TODO enable only after Cloudinary integration done
#  cloudinary:
#    mybucket:
#      - host: www.acme.co


      
cdnConfigurations:

  edgecast:
    token: "xxxxx-yyyyyyyyy-zzzzzzzzzz"
    hex: ABCDEF
    platform: small

  akamai:
    platform: production
    use_arl: False
    edgerc: ".edgerc"
    edgerc_section: "default"

   # To demonstrate how defaults are used, the configuration for highwinds is taken from the configuration file in vendors/highwinds
  
  cloudflare:
    email: "shalom@acme.net"
    apikey: "aaaaaaaaaaaaaaaaaaaaa"

  fastly:
    token: "xxxxxxxxxxxxxxxxxxxx"

  chinacache:
    token: "xxxxxxxxxxxxxxxxxxxx"

# TODO enable only after Cloudinary integration done
#  cloudinary:
#    cloud_name: "xxxxxxxxxxxxxxxxxxxx"
#    api_key:  "1234567890"
#    api_secret: "yyyyyyyyyyyyyy"